---
#
# Ansible managed
#
repository:
  description: Maintain your system by cleaning up.
  homepage: https://robertdebock.nl/
  topics: maintenance, security, system, ansible, molecule, tox, playbook
