---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap

  tasks:
    - name: create a file
      copy:
        dest: /tmp/some_file.txt
        content: "Some content"
        mode: "0644"
