---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: create a file
      copy:
        dest: /tmp/some_file.txt
        content: "Some content"

  roles:
    - role: robertdebock.bootstrap
